# Plugin made by SamGamerYT
# Website: https://samgameryt.com
# _   _ _       _     _   _   _ _     _                           
#| \ | (_)     | |   | | | | | (_)   (_)             _            
#|  \| |_  __ _| |__ | |_| | | |_ ___ _  ___  _ __ _| |_          
#| . ` | |/ _` | '_ \| __| | | | / __| |/ _ \| '_ \_   _|         
#| |\  | | (_| | | | | |_\ \_/ / \__ \ | (_) | | | ||_|           
#\_| \_/_|\__, |_| |_|\__|\___/|_|___/_|\___/|_| |_|              
#          __/ |                                                  
#         |___/                                                   
# _____                 _____                        __   _______ 
#/  ___|               |  __ \                       \ \ / /_   _|
#\ `--.  __ _ _ __ ___ | |  \/ __ _ _ __ ___   ___ _ _\ V /  | |  
# `--. \/ _` | '_ ` _ \| | __ / _` | '_ ` _ \ / _ \ '__\ /   | |  
#/\__/ / (_| | | | | | | |_\ \ (_| | | | | | |  __/ |  | |   | |  
#\____/ \__,_|_| |_| |_|\____/\__,_|_| |_| |_|\___|_|  \_/   \_/  
#                                                                 
#                                                                 
#
## Messages ##
no-permission: "&cYou do not have permission to run this command!"
config-reloaded: "&aYou have reloaded the configuration for NightVision+!"
usage-message:
  - "&&e&m*&f &9NightVision+&f &e&m*"
  - "&9/nv &f- &7Toggles night vision permanently."
  - "&&e&m*&f &9NightVision+&f &e&m*"
nightvision-toggled:
  message: "&bNight Vision has been {toggled}!"
  action-bar: "&5Night vision is currently {toggled}"
  enabled: "&aEnabled"
  disabled: "&cDisabled"
## Messages ##

## Features ##
send-action-bar: true
send-message: false
milk-bucket-remove: true
keep-effect-ondeath: true
## Features ##

## Core Features ##
check-for-updates: true
## Core Features ##